### PR TITLE
feat: Updated Roadmap (Oct23)

### PR DESCRIPTION
**Pull request by zishanaxioned**
@banuragaxioned @yvipinaxioned 

I have added a badge to add in the .mdx file if we want to show any badge.
We can add any text to it and provide a variant of how that badge looks on the page by adding a variant prop

Screenshot 2023-11-13 at 2 59 29 PM
Screenshot 2023-11-13 at 3 03 40 PM

Let me know if there are any changes required

### CODE REVIEW

**Comment by banuragaxioned** [comment]
@yvipinaxioned we discussed some changes here. Let me know once those are updated 🙏

**Comment by zishanaxioned** [comment]
> @yvipinaxioned we discussed some changes here. Let me know once those are updated 🙏

@banuragaxioned I have updated the page as discussed by @yvipinaxioned. You can see the comment on the PR. I have added some screenshots

**Comment by yvipinaxioned** [comment]
@zishanaxioned 
were you able to add "New" badge to the items?

**Comment by zishanaxioned** [comment]
> @zishanaxioned were you able to add "New" badge to the items?

Screenshot 2023-11-13 at 6 08 14 PM

**Review by banuragaxioned — APPROVED** [review]

**Pull request merged**
